#!/usr/bin/env python3
"""Convert a qgroup kprobe JSONL trace into a TLA+ data module.

Reads the JSON events emitted by tracing/bpftrace/btrfs_qgroup.bt and writes
BtrfsQgroupTraceData.tla, consumed by BtrfsQgroupTrace.tla to check that the
real kernel execution is an accepted behavior of BtrfsQgroupLifecycle.tla.

Transformations:
  - events are sorted by ts (bpftrace merges per-CPU buffers out of order)
  - only the model's observable actions are kept
  - events are split by the "fs" field (fs_info pointer): each btrfs
    filesystem is an independent qgroup state machine, and workloads like
    xfstests mount several at once (TEST_DEV + scratch). By default the
    group with quota activity (and the most events) is validated; --fs
    overrides. Traces without the field (older captures) form one group.
  - RescanWorker_* events are attributed to the model's single "worker"
    process regardless of which kworker tid executed the work item
  - other tids become user tasks "t<tid>"

Usage:
  python3 trace_to_tla.py trace.jsonl [-o OUTDIR] [--max-events N] [--fs FS]
"""
import argparse
import json
import sys
from pathlib import Path

OBSERVABLE = {
    "QuotaEnable_Enter", "QuotaEnable_Done",
    "QuotaDisable_Enter", "QuotaDisable_Done",
    "QgroupRescan_Enter", "QgroupRescan_Done",
    "RescanZeroTracking_Enter", "RescanZeroTracking_Done",
    # The btrfs_qgroup_wait_for_completion kprobe fires for out-of-TU
    # callers only (the rescan-wait ioctl and close_ctree at unmount);
    # the copy inlined into btrfs_quota_disable stays internal.
    "WaitRescanCompletion_Enter", "WaitRescanCompletion_Done",
    "FreeQgroupConfig_Enter", "FreeQgroupConfig_Done",
    "RescanWorker_Enter", "RescanWorker_Done",
}
WORKER_ACTIONS = {"RescanWorker_Enter", "RescanWorker_Done"}
QUOTA_OPS = {"QuotaEnable_Enter", "QuotaDisable_Enter", "QgroupRescan_Enter"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("trace", help="JSONL trace from btrfs_qgroup.bt (kprobe edition)")
    ap.add_argument("-o", "--outdir", default=str(Path(__file__).resolve().parent.parent
                                                  / "models/trace-validated"))
    ap.add_argument("--max-events", type=int, default=0,
                    help="truncate to the first N observable events (0 = all)")
    ap.add_argument("--fs", default=None,
                    help="validate this fs_info value (default: the group "
                         "with quota activity and the most events)")
    args = ap.parse_args()

    events = []
    skipped = 0
    for line in open(args.trace, errors="replace"):
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            e = json.loads(line)
        except json.JSONDecodeError:
            skipped += 1
            continue
        if e.get("action") in OBSERVABLE:
            events.append(e)

    # Split by filesystem: each fs_info is an independent state machine.
    groups = {}
    for e in events:
        groups.setdefault(str(e.get("fs", "?")), []).append(e)
    if len(groups) > 1 or (args.fs and args.fs in groups):
        for fs, evs in sorted(groups.items(), key=lambda kv: -len(kv[1])):
            active = any(e["action"] in QUOTA_OPS for e in evs)
            print(f"fs {fs}: {len(evs)} events"
                  + (" (quota-active)" if active else ""))
        if args.fs:
            if args.fs not in groups:
                sys.exit(f"--fs {args.fs} not in trace")
            events = groups[args.fs]
        else:
            active = [g for g in groups.values()
                      if any(e["action"] in QUOTA_OPS for e in g)]
            events = max(active or groups.values(), key=len)
        print(f"validating fs {events[0].get('fs', '?')} "
              f"({len(events)} of {sum(len(g) for g in groups.values())} events)")

    events.sort(key=lambda e: e.get("ts", 0))
    if args.max_events:
        events = events[: args.max_events]
    if not events:
        sys.exit("no observable events found in trace")

    def task(e):
        if e["action"] in WORKER_ACTIONS:
            return "worker"
        return f"t{e['tid']}"

    user_tasks = sorted({task(e) for e in events} - {"worker"})

    out = Path(args.outdir) / "BtrfsQgroupTraceData.tla"
    with open(out, "w") as f:
        f.write("---------------------- MODULE BtrfsQgroupTraceData ----------------------\n")
        f.write(f"(* Generated by trace_to_tla.py from {Path(args.trace).name}: "
                f"{len(events)} events, {len(user_tasks)} user tasks. *)\n")
        f.write("EXTENDS Sequences\n\n")
        f.write("TraceUserTasks == {")
        f.write(", ".join(f'"{t}"' for t in user_tasks))
        f.write("}\n\n")
        f.write("Trace == <<\n")
        recs = [f'[task |-> "{task(e)}", action |-> "{e["action"]}"]' for e in events]
        f.write(",\n".join("    " + r for r in recs))
        f.write("\n>>\n")
        f.write("=" * 74 + "\n")

    print(f"wrote {out}: {len(events)} events, {len(user_tasks)} user tasks"
          + (f", {skipped} unparseable lines skipped" if skipped else ""))


if __name__ == "__main__":
    main()
